Interm

diff --git a/lib/xvs/bootstrap/libexec/xvs b/lib/xvs/bootstrap/libexec/xvs
--- a/lib/xvs/bootstrap/libexec/xvs
+++ b/lib/xvs/bootstrap/libexec/xvs
@@ -1,17 +1,21 @@
-#! /usr/bin/env sh
+#! sh
 
 set -e
 set -u
-set -x
 
-if [ "${__XVS_RUNTIME_STATE-inactive}" != "active" ]; then
-  __XVS_PROJECT_BOOTSTRAP_DIR_LIBEXEC_PATH="$(cd "$(dirname "$(readlink "$0" || echo "$0")")" && pwd)"
-  __XVS_PROJECT_DIR_PATH="${__XVS_PROJECT_BOOTSTRAP_DIR_LIBEXEC_PATH}/.."
-  __XVS_PROJECT_DIR_BIN_NAME="bin"
-  __XVS_PROJECT_DIR_BIN_PATH="${__XVS_PROJECT_DIR_PATH}/${__XVS_PROJECT_DIR_BIN_NAME}"
-  exec "${__XVS_PROJECT_DIR_BIN_PATH}/xvs" ${@}
-else
+case "${__XVS_RUNTIME_STATE-inactive}" in
+  inactive)
+    __XVS_PROJECT_BOOTSTRAP_DIR_LIBEXEC_PATH="$(cd "$(dirname "$(readlink "$0" || echo "$0")")" && pwd)"
+    __XVS_PROJECT_DIR_PATH="${__XVS_PROJECT_BOOTSTRAP_DIR_LIBEXEC_PATH}/.."
+    __XVS_PROJECT_DIR_BIN_NAME="bin"
+    __XVS_PROJECT_DIR_BIN_PATH=${__XVS_PROJECT_DIR_PATH}/${__XVS_PROJECT_DIR_BIN_NAME}
 
+    export __XVS_RUNTIME_STATE="bootstrapping"
 
+    exec ${__XVS_PROJECT_DIR_BIN_PATH}/xvs $@
+    ;;
 
-fi
+  *)
+    echo "invalid state" && exit 1
+    ;;
+esac
